version: "3.3"

services:
  server:
    image: woahbase/alpine-pulseaudio:armv7l
    #restart: always
    devices:
     - /dev/bus/usb
     - /dev/snd
    network_mode: host
    cap_add:
     - NET_ADMIN
    volumes:
     - ./config/pulse:/etc/pulse
     - /etc/localtime:/etc/localtime:ro
     - /var/run/dbus:/var/run/dbus
    environment:
     - PUID=1000
     - PGID=1000
